apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resilience-platform-secrets
  namespace: resilience-platform
  labels:
    app.kubernetes.io/name: resilience-platform
    app.kubernetes.io/component: api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-vault
    kind: ClusterSecretStore
  target:
    name: resilience-platform-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: resilience-platform
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: resilience-platform/production
        property: database_url
    - secretKey: REDIS_URL
      remoteRef:
        key: resilience-platform/production
        property: redis_url
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: resilience-platform/production
        property: celery_broker_url
