apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - serviceaccount.yaml
  - issuer.yaml
  - certificate.yaml
  - service.yaml
  - ingress.yaml
  - migration-job.yaml
  - cleanup-cronjob.yaml
  - deployment.yaml
  - poddisruptionbudget.yaml
  - hpa.yaml
