apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - ../configmap.yaml
  - test-secret.yaml
  - test-dependencies.yaml
  - ../serviceaccount.yaml
  - ../service.yaml
  - ../deployment.yaml

images:
  - name: ghcr.io/alex-developer-git/microservice-resilience-platform
    newName: resilience-platform
    newTag: latest

patches:
  - target:
      kind: ConfigMap
      name: resilience-platform-config
    patch: |-
      - op: replace
        path: /data/ENVIRONMENT
        value: test
      - op: replace
        path: /data/OTEL_ENABLED
        value: "false"
      - op: replace
        path: /data/RATE_LIMIT_GLOBAL_REQUESTS
        value: "10"
      - op: replace
        path: /data/RATE_LIMIT_HEALTH_CHECK_REQUESTS
        value: "2"
  - target:
      kind: Deployment
      name: resilience-platform-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/initContainers/0/imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
