apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../namespace.yaml
  - ../configmap.yaml
  - ../external-secret.yaml
  - ../serviceaccount.yaml
  - ../issuer.yaml
  - ../certificate.yaml
  - ../service.yaml
  - ../networkpolicy.yaml
  - ../ingress.yaml
  - ../ingress-static.yaml
  - ../migration-job.yaml
  - ../cleanup-cronjob.yaml
  - rollout.yaml
  - analysis-template.yaml
  - ../poddisruptionbudget.yaml
  - ../hpa.yaml

patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: resilience-platform-api
    patch: |-
      - op: replace
        path: /spec/scaleTargetRef/apiVersion
        value: argoproj.io/v1alpha1
      - op: replace
        path: /spec/scaleTargetRef/kind
        value: Rollout
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 10
